# Generated by Django 4.2

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("age", models.IntegerField(default=0)),
                ("phone_number", models.CharField(max_length=20)),
                ("monthly_salary", models.DecimalField(decimal_places=2, max_digits=15)),
                ("approved_limit", models.DecimalField(decimal_places=2, max_digits=15)),
                ("current_debt", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=15)),
            ],
            options={
                "db_table": "core_customer",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("tenure", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("monthly_installment", models.DecimalField(decimal_places=2, max_digits=15)),
                ("emis_paid_on_time", models.IntegerField(default=0)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loans", to="core.customer")),
            ],
            options={
                "db_table": "core_loan",
                "ordering": ["-start_date"],
            },
        ),
    ]
